print('=-'*10)
print('EMPRÉSTIMO BANCÁRIO')
print('=-'*10)
val = int(input('Informe o valor da Casa: '))
sal = int(input('Informe o salário do comprador: '))
anos = int(input('Informe em quantos anos deseja pagar: '))
